- hosts: local1
  tasks:
  - name: Ansible copy file to remote server1
    copy:
      src: a.txt
      dest: /home/ubuntu/Kartik
      
- hosts: local2
  tasks:
  - name: Ansible copy file to remote server2
    copy:
      src: b.txt
      dest: /home/ubuntu/
