- hosts: local1
  vars:
    src_file: 
      - info0.txt
      - info1.txt
      - info2.txt
  tasks:
  - name: Ansible copy file to remote server
    copy:
      src: {{ filename }}
      dest: /home/ubuntu/kartik/
      
- hosts: local2
  vars:
    src_file: 
      - info0.txt
      - info1.txt
      - info2.txt
  tasks:
  - name: Ansible copy file to remote server
    copy:
      src: {{ filename }}
      dest: /home/ubuntu/kartik/
