- hosts: local1
  tasks:
  - name: Ansible copy file to remote server1
    copy:
      src: "{{ filename }}"
      dest: /home/ubuntu/Kartik
      
- hosts: local2
  tasks:
  - name: Ansible copy file to remote server2
    copy:
      src: "{{ filename }}"
      dest: /home/ubuntu/Kartik
