- hosts: local
  vars:
    src_file: 
      - info0.txt
      - info1.txt
      - info2.txt
  tasks:
  - name: Ansible copy file to remote server
    copy:
      src: ansible_proj/a.txt
      dest: /home/ec2-user/kartik/
